# Generated by Django 3.1 on 2021-12-12 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('tmId', models.AutoField(primary_key=True, serialize=False)),
                ('pId', models.CharField(default='AMS', max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='/media/default/profile.jpg', null=True, upload_to=user.models.upload_location)),
                ('maritalStatus', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='single', max_length=25)),
                ('body_Type', models.CharField(max_length=15)),
                ('height', models.CharField(max_length=15)),
                ('weight', models.CharField(max_length=15)),
                ('matrimonyProfileFor', models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('self', 'Self')], default='personal', max_length=25)),
                ('drink', models.CharField(max_length=15)),
                ('smoke', models.CharField(max_length=15)),
                ('dateOfBirth', models.DateTimeField(verbose_name='Date of Birth/Time - Format : YYYY-MM-DD HH:MM')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField(default=0)),
                ('motherTongue', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=15)),
                ('blood_group', models.CharField(default='not specified', max_length=20)),
                ('diet', models.CharField(max_length=20)),
                ('religion', models.CharField(choices=[('hindu', 'Hindu'), ('cristian', 'Cristian'), ('muslim', 'Muslim'), ('sikh', 'Sikh'), ('buddhist', 'Buddhist')], max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('sub_caste', models.CharField(max_length=25)),
                ('placeOfBirth', models.CharField(max_length=30)),
                ('rassi', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=50)),
                ('education_detail', models.CharField(max_length=50)),
                ('occupation_detail', models.CharField(max_length=100)),
                ('annual_income', models.CharField(default='not specified', max_length=20)),
                ('current_location', models.CharField(max_length=25)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('no_of_sisters', models.IntegerField(default=0)),
                ('no_of_brother', models.IntegerField(default=0)),
                ('p_age_min', models.IntegerField(default=0)),
                ('p_age_max', models.IntegerField(default=0)),
                ('p_Marital_Status', models.CharField(max_length=10)),
                ('p_Body_Type', models.CharField(max_length=25)),
                ('p_Complexion', models.CharField(max_length=25)),
                ('p_Height', models.CharField(max_length=25)),
                ('p_Diet', models.CharField(max_length=25)),
                ('p_Manglik', models.CharField(max_length=25)),
                ('p_Religion', models.CharField(max_length=25)),
                ('p_Caste', models.CharField(max_length=25)),
                ('p_Mother_Tongue', models.CharField(max_length=25)),
                ('p_Education', models.CharField(max_length=25)),
                ('p_Country_Of_Residence', models.CharField(max_length=25)),
                ('p_State', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
